// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TlalocAi.Telemetry.Infrastructure;

#nullable disable

namespace TlalocAi.Telemetry.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260612051548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.ActuatorSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActuatorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("IsOn")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("telemetry_actuator_snapshots", (string)null);
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("telemetry_experiments", (string)null);
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.LevelMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MeasurementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("telemetry_level_measurements", (string)null);
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("FlowLpm")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("PumpOn")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalLiters")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "TimestampUtc");

                    b.ToTable("telemetry_measurements", (string)null);
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Infrastructure.DeviceRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("devices_devices", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.ActuatorSnapshot", b =>
                {
                    b.HasOne("TlalocAi.Telemetry.Domain.Measurement", null)
                        .WithMany("Actuators")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.LevelMeasurement", b =>
                {
                    b.HasOne("TlalocAi.Telemetry.Domain.Measurement", null)
                        .WithMany("Levels")
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TlalocAi.Telemetry.Domain.Measurement", b =>
                {
                    b.Navigation("Actuators");

                    b.Navigation("Levels");
                });
#pragma warning restore 612, 618
        }
    }
}
