[platformio]
default_envs = esp32-a

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32-a]
build_flags =
  -D BOARD_ID=\"esp32-a\"

[env:esp32-b]
build_flags =
  -D BOARD_ID=\"esp32-b\"
